### ISSUE TITLE
遇到TypeError: Cannot set property 'atob' of undefined错误

### ISSUE THREAD

**Issue by artwl** [LoS-Light/CocosCreator3_SingleHtmlPlayable#1]
你好，最近也在做cocos 3d打包成单文件的功能，看了你的分享 https://forum.cocos.org/t/topic/111354 ，用跟你类似的方式测试了一下，但出现了 `TypeError: Cannot set property 'atob' of undefined`错误，希望能跟你交流请教一下：

<img width="1333" alt="WX20210525-165911@2x" src="https://user-images.githubusercontent.com/982563/119470306-cabd5e80-bd7a-11eb-89f3-6f63881f8889.png">

**Comment by LoS-Light** [comment]
> 你好，最近也在做cocos 3d打包成单文件的功能，看了你的分享 https://forum.cocos.org/t/topic/111354 ，用跟你类似的方式测试了一下，但出现了 `TypeError: Cannot set property 'atob' of undefined`错误，希望能跟你交流请教一下：
> 
> <img alt="WX20210525-165911@2x" width="1333" src="https://user-images.githubusercontent.com/982563/119470306-cabd5e80-bd7a-11eb-89f3-6f63881f8889.png">



atob是一个浏览器内建函数，
按照您图片上的错误显示，Cannot set property 'atob' of undefined，很明显是说未定义atob，
这错误可能是您用法有误所造成的，您可以确认一下这w3school的atob使用后再试一次看看。
https://www.w3schools.com/jsref/met_win_atob.asp

**Comment by artwl** [comment]
> > 你好，最近也在做cocos 3d打包成单文件的功能，看了你的分享 https://forum.cocos.org/t/topic/111354 ，用跟你类似的方式测试了一下，但出现了 `TypeError: Cannot set property 'atob' of undefined`错误，希望能跟你交流请教一下：
> > <img alt="WX20210525-165911@2x" width="1333" src="https://user-images.githubusercontent.com/982563/119470306-cabd5e80-bd7a-11eb-89f3-6f63881f8889.png">
> 
> atob是一个浏览器内建函数，
> 按照您图片上的错误显示，Cannot set property 'atob' of undefined，很明显是说未定义atob，
> 这错误可能是您用法有误所造成的，您可以确认一下这w3school的atob使用后再试一次看看。
> https://www.w3schools.com/jsref/met_win_atob.asp

非常感谢回复，我今天又调了一下，已经可以显示启动页了，但场景加载还是会失败。

![image](https://user-images.githubusercontent.com/982563/119628290-8b0c7a80-be3f-11eb-8e03-446f81803adb.png)

我用的是最新的 3.1.0 版本。我也在关注cocos转试玩广告这一块，希望能进一步交流。我的联系方式(wx：artwl_)

**Comment by LoS-Light** [comment]
因最近公司工作转换的缘故，
都在制作2.4.5版本的playable，
故很久没有继续开发3.0.1打包工具了，
未来工作到一段落后才会回来继续开发，
所以本人也不清楚3.1.0作了哪些引擎更动，
而从您上方提供的错误来看，
也无法从这错误获得任何有用的讯息，
所以这部分我也无能为力。

**Comment by artwl** [comment]
> 因最近公司工作转换的缘故，
> 都在制作2.4.5版本的可玩，
> 故很久没有继续开发3.0.1打包工具了，
> 未来工作到一段落后才会回来继续开发，
> 所以本人也不清楚3.1.0作些引擎更动，
> 而从您上方提供的错误来看，
> 也无法从这错误获得任何有用的讯息，
> 所以这部分我也无能为力。

理解，能否加个微信（artwl_），后续可以互相交流

**Comment by LoS-Light** [comment]
> > 因最近公司工作转换的缘故，
> > 都在制作2.4.5版本的可玩，
> > 故很久没有继续开发3.0.1打包工具了，
> > 未来工作到一段落后才会回来继续开发，
> > 所以本人也不清楚3.1.0作些引擎更动，
> > 而从您上方提供的错误来看，
> > 也无法从这错误获得任何有用的讯息，
> > 所以这部分我也无能为力。
> 
> 理解，能否加个微信（artwl_），后续可以互相交流

wxid_v9v730snxo3e12

**Comment by artwl** [comment]
> wxid_v9v730snxo3e12

感谢回复，你这个是微信ID，不是微信号，加不了。。。，你可以加一下我，微信号是 artwl_

**Comment by LoS-Light** [comment]
无法确认您的身份
是否能给点身分讯息

**Comment by artwl** [comment]
> 无法确认您的身份
> 是否能给点身分讯息

我们也在做试玩广告相关业务，算是同行吧，个人信息发在这里全是公开的。。。

**Comment by LoS-Light** [comment]
那我要怎么知道加的是不是您，
我微信少用，较常用QQ，
如果可以用QQ的话，
加一下3408468126，
然后回个您的身份方便我确认，
谢谢。
